# Generated by Django 3.0.8 on 2020-07-22 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=250, verbose_name='Ингредиент')),
                ('calories', models.IntegerField(verbose_name='Калорийность')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=250, verbose_name='Название заведения')),
                ('restaurant_address', models.CharField(max_length=250, verbose_name='Адрес заведения')),
                ('works_from', models.TimeField(verbose_name='Работает с:')),
                ('works_until', models.TimeField(verbose_name='Работает до:')),
                ('restaurant_img', models.ImageField(upload_to='', verbose_name='Изображение заведения')),
                ('coord_one', models.FloatField(verbose_name='Coord one')),
                ('coord_two', models.FloatField(verbose_name='Coord two')),
                ('restaurant_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=250, verbose_name='Название блюда')),
                ('dish_img', models.ImageField(upload_to='', verbose_name='Изображение блюда')),
                ('dish_total_calories', models.PositiveIntegerField(verbose_name='Суммарная калорийность')),
                ('dish_price', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('dish_ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Ingredient')),
                ('restaurant_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Restaurant')),
            ],
        ),
    ]
