# Generated by Django 3.0.8 on 2020-07-23 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('food', '0001_initial'), ('food', '0002_auto_20200722_2034'), ('food', '0003_auto_20200722_2152'), ('food', '0004_auto_20200722_2233'), ('food', '0005_auto_20200722_2251'), ('food', '0006_auto_20200723_0254'), ('food', '0007_auto_20200723_0819'), ('food', '0008_auto_20200723_0841')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=250, verbose_name='Ингредиент')),
                ('calories', models.IntegerField(verbose_name='Калорийность')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=250, verbose_name='Название блюда')),
                ('dish_img', models.ImageField(upload_to='', verbose_name='Изображение блюда')),
                ('dish_total_calories', models.PositiveIntegerField(null=True, verbose_name='Суммарная калорийность')),
                ('dish_price', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('dish_ingredients', models.ManyToManyField(to='food.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=250, verbose_name='Название заведения')),
                ('restaurant_address', models.CharField(max_length=250, verbose_name='Адрес заведения')),
                ('works_from', models.TimeField(verbose_name='Работает с:')),
                ('works_until', models.TimeField(verbose_name='Работает до:')),
                ('restaurant_img', models.ImageField(upload_to='', verbose_name='Изображение заведения')),
                ('coord_one', models.FloatField(verbose_name='Coord one')),
                ('coord_two', models.FloatField(verbose_name='Coord two')),
                ('restaurant_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('restaurant_dishes', models.ManyToManyField(to='food.Dish')),
                ('average_dishes_price', models.IntegerField(null=True, verbose_name='Средняя стоимость блюда')),
            ],
        ),
    ]
