# Generated by Django 3.0.8 on 2020-07-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20200722_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='restaurant_dish',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_dishes',
            field=models.ManyToManyField(to='food.Dish'),
        ),
    ]
