# Generated by Django 3.0.8 on 2020-07-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20200722_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='average_dishes_price',
            field=models.IntegerField(null=True, verbose_name='Средняя стоимость блюда'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_dishes',
            field=models.ManyToManyField(null=True, to='food.Dish'),
        ),
    ]
