# Generated by Django 3.0.8 on 2020-07-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20200722_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_dishes',
            field=models.ManyToManyField(to='food.Dish'),
        ),
    ]
