# Generated by Django 3.0.8 on 2020-07-23 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_auto_20200723_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dish_ingredients',
            field=models.ManyToManyField(to='food.Ingredient'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_dishes',
            field=models.ManyToManyField(to='food.Dish'),
        ),
    ]
