# Generated by Django 3.0.8 on 2020-07-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_auto_20200723_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='dish_name',
            new_name='name',
        ),
    ]
