# Generated by Django 3.0.8 on 2020-07-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_auto_20200723_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='coord_one',
            field=models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Coord one'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='coord_two',
            field=models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Coord two'),
        ),
    ]
