# Generated by Django 3.0.8 on 2020-07-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_auto_20200724_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_img',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение заведения'),
        ),
    ]
