# Generated by Django 3.0.8 on 2020-07-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_auto_20200724_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_dishes',
            field=models.ManyToManyField(blank=True, to='food.Dish'),
        ),
    ]
