# Generated by Django 3.0.8 on 2020-07-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_auto_20200729_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Longitude'),
        ),
    ]
